drop user camel;
create tablespace camel_tabspace datafile 'camel_tabspace.dat' size 10M autoextend on;
create temporary tablespace camel_tabspace_temp tempfile 'camel_tabspace_temp.dat' size 5M autoextend on;
create user camel identified by Abcd1234 default tablespace camel_tabspace temporary tablespace camel_tabspace_temp;
grant create session to camel;
grant create table to camel;
grant unlimited tablespace to camel;
grant all privileges to camel;

CREATE TABLE customer (
    customer_id NUMBER GENERATED by default on null as IDENTITY,  
    preferred_language varchar2(50) NOT NULL,  
    in_perception NUMBER(1,0) NOT NULL,  
  CONSTRAINT customer_id_pk PRIMARY KEY (customer_id)  
);  

INSERT INTO CUSTOMER (preferred_language, in_perception) VALUES ('en', 1);
